behaviors:
  Unko:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
      curiosity:
        strength: 0.02
        gamma: 0.99
        encoding_size: 256
      gail:
        strength: 0.01
        gamma: 0.99
        encoding_size: 128
        demo_path: Demonstrations/demonko.demo
    behavioral_cloning:
      demo_path: Demonstrations/demonko.demo
      strength: 0.5
      steps: 150000
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 1.0e7
    time_horizon: 128
    summary_freq: 20000
    threaded: true
    self_play:
      save_steps: 50000
      team_change: 100000
      swap_steps: 2000
      window: 15
      play_against_latest_model_ratio: 0.5
      initial_elo: 1000.0